### ISSUE TITLE
Css 画一个三角形

### ISSUE THREAD

**Issue by lgwebdream** [lgwebdream/FE-Interview#413]

**Comment by lgwebdream** [comment]
<h3 align="center">扫描下方二维码，获取答案以及详细解析，同时可解锁800+道前端面试题。</h3>
<div align="center">
<img src="http://img-static.yidengxuetang.com/wxapp/qr-ques/qid-257.png"  width="260px">
</div>

**Comment by guoguoqiqi** [comment]
`<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-16">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    .triangle {
      width: 0;
      height: 0;
      border-top: 200px solid transparent;
      border-right: 200px solid transparent;
      border-bottom: 200px solid green;
      border-left: 200px solid transparent;
    }
  </style>
</head>
<body>
  <div class="triangle"></div>
</body>
</html>`

**Comment by guoguoqiqi** [comment]
`console.log()`

**Comment by guoguoqiqi** [comment]
```css
 .triangle {
      width: 0;
      height: 0;
      border-top: 200px solid transparent;
      border-right: 200px solid transparent;
      border-bottom: 200px solid green;
      border-left: 200px solid transparent;
 }
```
```html
<div class="triangle"></div>
```
