### ISSUE TITLE
清除浮动的方式

### ISSUE THREAD

**Issue by lgwebdream** [lgwebdream/FE-Interview#498]

**Comment by lgwebdream** [comment]
<h3 align="center">扫描下方二维码，获取答案以及详细解析，同时可解锁800+道前端面试题。</h3>
<div align="center">
<img src="http://img-static.yidengxuetang.com/wxapp/qr-ques/qid-404.png"  width="260px">
</div>

**Comment by GuoLizhi** [comment]
### 1. 空元素

```css
.clear {
  clear: both;
}
```

### 2.overflow

```css
.clear {
  overflow:hidden;
}
```

### 3. after伪类

```css
.clearfix:after {
    content: ' ';
    height: 0;
    display: block;
    clear: both;
}
```

### 4. 给父元素也添加上浮动
