### ISSUE TITLE
Day160:动手实现一个左右固定100px，中间自适应的三列布局？(至少三种)

### ISSUE THREAD

**Issue by Genzhen** [lgwebdream/FE-Interview#974]

**Comment by Clect** [comment]
```
<div id="father">
      <div id="son"></div>
</div>
```

1、
> 用calc
> #father {
>   width: 600px;
>   height: 200px;
>   background-color: black;
> }
> 
> #son {
>   width: calc(100% - 200px);
>   height: 100%;
>   background-color: green;
>   margin: 0 100px;
> }

2、
> 用flex
> #father {
>   width: 600px;
>   height: 200px;
>   background-color: black;
>   display: flex;
> }
> 
> #son {
>   flex: 1;
>   height: 100%;
>   margin: 0 100px;
>   background-color: green;
> }

3、
> 用padding
> #father {
>   width: 400px;
>   height: 200px;
>   background-color: black;
>   padding: 0 100px;
> }
> 
> #son {
>   width: 100%;
>   height: 100%;
>   background-color: green;
> }

**Comment by lightzhu** [comment]
1.float
2.position:absolute
3.flex
4.display:table
5.display:grid
<section class="table">
    <style>
      .table {
        display: table;
        width: 100%;
      }

      .table>div {
        display: table-cell;
        width: 200px;
        background: pink;
      }

      .table .center {
        display: table-cell;
      }
    </style>
    <div class='left'></div>
    <article class='center'>
      shjdkadfkjafdkasflkslkfskld
      table布局
    </article>
    <div class='right'></div>
  </section>
  <section class="grid">
    <style>
      .grid {
        display: grid;
        grid-template-columns: 200px auto 200px;
      }

      .grid>div {
        background: pink;
      }
    </style>
    <div class='left'></div>
    <article class='center'>
      shjdkadfkjafdkasflkslkfskld
    </article>
    <div class='right'></div>
  </section>

**Comment by GuoLizhi** [comment]
整体的html

```html
  <div class="container">
    <div class="left"></div>
    <div class="center"></div>
    <div class="right"></div>
  </div>
```

### 方法1： flex

```css
.container {
  display: flex;
  height: 100px;
}
.container * {
  height: 100px;
}
.left,
.right {
  flex-basis: 100px;
  background-color: aquamarine;
}
.center {
  flex-grow: 1;
  background: red;
}
```

### 方法2: position

```css
.container {
  height: 100px;
  position: relative;
}
.container * {
  height: 100px;
  position: absolute;
  top: 0;
}
.left,
.right {
  background-color: aquamarine;
  width: 100px;
}
.left {
  left: 0;
}
.right {
  right: 0;
}
.center {
  background: red;
  left: 100px;
  right: 100px;
}
```

### 方法3：float+margin

如果用浮动的话，html布局要稍微调整一下

```html
  <div class="container">
    <div class="left"></div>
    <div class="right"></div>
    <div class="center"></div>
  </div>
```

css如下

```css
.container {
  height: 100px;
  overflow: hidden;
}
.container * {
  height: 100px;
}
.left,
.right {
  background-color: aquamarine;
  width: 100px;
}
.left {
  float: left;
}
.right {
  float: right;
}
.center {
  background: red;
  margin: 0 100px;
}
```

### 方法4：grid

```css
.container {
  height: 100px;
  overflow: hidden;
  display: grid;
  grid-template-columns: 100px auto 100px;
}
.container * {
  height: 100px;
}
.left,
.right {
  background-color: aquamarine;
  width: 100px;
}
.center {
  background: red;
}
```

但grid布局兼容性不太友好，参考caniuse

![image](https://user-images.githubusercontent.com/52066214/108939185-4af4fa80-768c-11eb-9e06-133211882c88.png)
